# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in the python scripts.
root_dir: ${oc.env:PROJECT_ROOT,.}

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
#output_dir: ${hydra:runtime.output_dir}
output_dir: ${hydra:runtime.output_dir} # see https://github.com/facebookresearch/hydra/issues/2226#issuecomment-1135529393

# path to working directory
work_dir: ${hydra:runtime.cwd}

# path to hf cache
cache_dir: ${paths.root_dir}/cache/