default_language_version:
  python: python3.8
exclude: (^docs/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        types: [text]
        stages: [commit, push, manual]
      - id: end-of-file-fixer
        name: Fix End of Files
        types: [text]
        stages: [commit, push, manual]
      - id: check-yaml
        name: Check Yaml
        types: [yaml]
      - id: check-toml
        name: Check Toml
        types: [toml]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        args: [--skip-string-normalization, --config, ./pyproject.toml]
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: python -m flake8
        language: system
        types: [python]

      - id: mypy # default config comes from setup.cfg
        name: mypy
        entry: python -m mypy
        language: system
        types: [python]
        exclude: "test_.*" # exclude all test files form type checking

      - id: docstr-coverage
        name: docstr-coverage
        entry: docstr-coverage
        types: [python]
        exclude: "test_.*"
        language: system
        args: [--fail-under, "50"] # fail if less than 50 of code has docstrings
        log_file: docstring-coverage.txt

      - id: darglint # default config comes from .darglint
        name: darglint
        entry: python -m darglint
        args: [-v, "2"]
        types: [python]
        language: system
        exclude: "test_.*"
